hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("swaync")
    hl.exec_cmd("lact")
    hl.exec_cmd("wl-paste --watch cliphist store &")
    hl.exec_cmd("steam")
    hl.exec_cmd("nwg-dock-hyprland -p bottom -a center -i 52 -mb 8 -d -nolauncher")
    hl.exec_cmd("ags run ~/.config/ags")
end)
