# Execute your favorite apps at launch
exec-once = waybar
exec-once = hyprpaper
exec-once = swaync
exec-once = lact
exec-once = wl-paste --watch cliphist store &
exec-once = awww-daemon
exec-once = openrgb
exec-once = steam