# See https://wiki.hyprland.org/Configuring/Variables/ for more
decoration {
    rounding = 0
    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        contrast = 1.05
        brightness = 1.05
        vibrancy = 0.25
        vibrancy_darkness = 0.0
        noise = 0.008
    }
}
