# See https://wiki.hyprland.org/Configuring/Monitors/
monitor=,1920x1080@165,auto,1, vrr, 2
# Configuración optimizada según la Wiki de Hyprland
# monitor=, modeline 382.75 1920 1968 2000 2080 1080 1083 1088 1114 +hsync -vsync, auto, 1, vrr, 2