# See https://wiki.hyprland.org/Configuring/Monitors/
# ==========================================
# 1. GEOMETRÍA DE MONITORES (Secundario a la Izquierda)
# ==========================================
# Monitor Secundario (Izquierda, Punto de origen 0,0)
monitor = HDMI-A-1, 1600x900@60, 0x0, 1, vrr, 0

# Monitor Principal (Derecha, Empieza en la coordenada X 1600)
monitor = DP-3, 1920x1080@120, 1600x0, 1, vrr, 1

# ==========================================
# 2. ENRUTAMIENTO DE ESPACIOS DE TRABAJO (WORKSPACES)
# ==========================================
# Monitor Principal (DP-3) - Espacios 1 al 5
workspace = 1, monitor:DP-3, default:true
workspace = 2, monitor:DP-3
workspace = 3, monitor:DP-3
workspace = 4, monitor:DP-3
workspace = 5, monitor:DP-3

# Monitor Secundario (HDMI-A-1) - Espacios 6 al 10
workspace = 6, monitor:HDMI-A-1, default:true
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1
