# -----------------------------------------------------
# BOCCHIZILLA WALLPAPER
# -----------------------------------------------------

# Ejecutar plugins
exec-once = hyprpm reload

# Ejecutar hyprwinwrap
plugin {
    hyprwinwrap {
	class = bocchi-bg
    }
}

# Lanzamiento al iniciar sesion
exec-once = env chromium --app="file:///home/jwalters/.config/hypr/wallpaper/bocchizilla_rebirth/index.html" --class="bocchi-bg" --user-data-dir="/tmp/bocchi-wallpaper" --ozone-platform=x11 & disown

# Reglas de la ventana
windowrule {
    name = reglas_bocchi_fondo

    match:class = ^(bocchi-bg)$

    float = 1
    pin = 1
    no_focus = 1
    no_initial_focus = 1

    no_blur = 1
    no_shadow = 1

    size = 1920 1080
    move = 0 0
}
