# -----------------------------------------------------
# BOCCHIZILLA WALLPAPER
# -----------------------------------------------------

# Ejecutar 'wewa'

exec-once = wewa /home/jwalters/.config/hypr/wallpaper/bocchizilla_rebirth/index.html

# Ejecutar OpenRGB

exec-once = openrgb --profile ambilight --startminimized
