# -----------------------------------------------------
# BOCCHIZILLA WALLPAPER ENGINE (Modular v4.0)
# -----------------------------------------------------

# 1. Cargar plugins
exec-once = hyprpm reload

# 2. Configuración del Wrap
plugin {
    hyprwinwrap {
	class = bocchi-bg
    }
}

# 3. Lanzamiento Automático (Limpio y Aislado)
exec-once = env chromium --app="file:///home/jwalters/.config/hypr/wallpaper/bocchizilla_rebirth/index.html" --class="bocchi-bg" --user-data-dir="/tmp/bocchi-wallpaper" --ozone-platform=x11 & disown

# -----------------------------------------------------
# BOCCHIZILLA WALLPAPER - REGLAS DE HIERRO
# -----------------------------------------------------

windowrule {
    # El identificador DEBE ser la primera línea
    name = reglas_bocchi_fondo
    
    # Selector
    match:class = ^(bocchi-bg)$
    
    # Comportamiento (Con valores explícitos)
    float = 1
    pin = 1
    no_focus = 1
    no_initial_focus = 1
    
    # Estética (Snake_case)
    no_blur = 1
    no_shadow = 1
    
    # Posicionamiento
    size = 1920 1080
    move = 0 0
}
