windowrule {
    name = panel_diagnostico
    match:class = ^(popup-fetch)$
    float = true
    size = 700 200
    
    # OPCIÓN A: Libre movimiento, pero nace anclado abajo a la izquierda
    move = 20 100%-470
    
    # OPCIÓN B: Si prefieres que nazca en el centro, borra el 'move' y usa esto:
    # center = true
}
