windowrule {
    name = panel_diagnostico
    match:class = ^(popup-fetch)$
    float = true
    size = 700 200
    
    # OPCIÓN A: Libre movimiento, pero nace anclado abajo a la izquierda
    move = 20 100%-470
    
    # OPCIÓN B: Si prefieres que nazca en el centro, borra el 'move' y usa esto:
    # center = true
    
}

layerrule {
    name = rofi-slide-anim
    match:namespace = ^rofi$
    animation = slide left
}

layerrule {
    name = blur-waybar
    match:namespace = ^waybar$
    blur = on
    ignore_alpha = 0.2
}

layerrule {
    name = swaync_control_blur
    match:namespace = ^swaync-control-center$
    animation = slide right
}

layerrule {
    name = nwg_dock_rules
    match:namespace = ^nwg-dock$
    blur = on
    ignore_alpha = 0.2
    animation = slide bottom
}
