# ---------------------------------------------------------
# ~/.config/kitty/kitty.conf
# ---------------------------------------------------------

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
disable_ligatures never
font_size 12

# --- Temas ---

# include tokyo-night
include gruvbox-light-custom

# ---------------------------------------------------------
# Estructura de Pestañas (Emulación de Navegador Web)
# ---------------------------------------------------------
tab_bar_edge            top
tab_bar_style           separator
tab_separator           " "
tab_bar_min_tabs        1

# ---------------------------------------------------------
# Paleta de Pestañas (Gruvbox Light Desaturado)
# ---------------------------------------------------------
active_tab_foreground   #fbf1c7
active_tab_background   #393939
active_tab_font_style   bold

inactive_tab_foreground #75706b
inactive_tab_background #d5c4a1
inactive_tab_font_style normal

tab_bar_background      #fbf1c7
