windowrule {
    name = panel_diagnostico
    match:class = ^(popup-fetch)$
    float = true
    size = 900 380
}
layerrule {
    name = blur-waybar
    match:namespace = ^waybar$
    blur = off
    ignore_alpha = 0.02
}
layerrule {
    name = blur-liquid-dock
    match:namespace = ^liquid-dock$
    blur = on
    ignore_alpha = 0.2
}
layerrule {
    name = rules-rofi
    match:namespace = ^rofi$
    animation = none
}
layerrule {
    name = swaync_control_blur
    match:namespace = ^swaync-control-center$
    animation = slide right
}
layerrule {
    name = nwg_dock_rules
    match:namespace = ^nwg-dock$
    blur = on
    ignore_alpha = 0.04
    animation = slide bottom
}
layerrule {
    name = swaync_center
    match:namespace = ^swaync-control-center$
    blur = on
    ignore_alpha = 0.5
}
layerrule {
    name = swaync_notif
    match:namespace = ^swaync-notification-window$
    blur = on
    ignore_alpha = 0.1
}
